### ISSUE TITLE
Latest version link is broken

### ISSUE THREAD

**Issue by kapsh** [jtalks-org/pochta#13]
"Download latest version" link in readme file points to http://repo.jtalks.org/content/repositories/releases/org/jtalks/jtalks-pochta/1.4/jtalks-pochta-1.4.jar, but this URL gives "404 - Path /org/jtalks/jtalks-pochta/1.4/jtalks-pochta-1.4.jar not found in local storage of repository "Releases" [id=releases]" message.

**Comment by masyan** [comment]
fixed, thx.
